coqui:
  model: /opt/deepspeech/model.tflite
  scorer: /opt/deepspeech/huge-vocabulary.scorer
server:
  http:
    host: "0.0.0.0"
    port: 9090
    request_max_size: 10485760
log:
  level:
    - logger: deepspeech_server
      level: DEBUG

